public with sharing class javascriptLearning {
    public List<String> lstAssignToArray    {get;set;}
    
    public javascriptLearning()
    {
        lstAssignToArray = new List<String>();
        lstAssignToArray.add('ABC');
        lstAssignToArray.add('DEF');
        lstAssignToArray.add('GHI');
        lstAssignToArray.add('JKL');
        lstAssignToArray.add('MNO');
        lstAssignToArray.add('PQR');
        lstAssignToArray.add('STU');
        lstAssignToArray.add('VWX');
        lstAssignToArray.add('YZ');
    }
}